// examples/vue/src/app.vue
<script setup lang="ts">
import InkContracts from "./ink-contracts.vue";
import MutationSection from "./mutation-section.vue";
import QuerySection from "./query-section.vue";
import SolidityContracts from "./solidity-contracts.vue";
import WalletConnection from "./wallet-connection.vue";
import type { ChainId } from "@reactive-dot/core";
import {
  provideChain,
  useChainIds,
  useQueryErrorResetter,
  watchMutation,
} from "@reactive-dot/vue";
import { onErrorCaptured, ref } from "vue";

const chainIds = useChainIds();
const selectedChainId = ref<ChainId>("polkadot");
provideChain(selectedChainId);

const hasError = ref(false);
const { execute: resetError } = useQueryErrorResetter();
onErrorCaptured(() => (hasError.value = true));

// Useful tracking all submitted transaction, i.e. for toast notification
// eslint-disable-next-line no-undef
watchMutation((event) => console.log(event));
</script>

<template>
  <div>
    <label>
      Chain
      <select v-model="selectedChainId">
        <option v-for="chainId in chainIds" :key="chainId" :value="chainId">
          {{ chainId }}
        </option>
      </select>
    </label>
  </div>
  <article v-if="hasError">
    <header>
      <strong>Oops, something went wrong!</strong>
    </header>
    <button
      @click="
        resetError();
        hasError = false;
      "
    >
      Retry
    </button>
  </article>
  <Suspense v-else :key="selectedChainId">
    <div>
      <WalletConnection />
      <QuerySection />
      <MutationSection />
    </div>
    <template #fallback><p>Loading chain...</p></template>
  </Suspense>
  <Suspense>
    <InkContracts />
    <template #fallback><p>Loading Ink! contracts...</p></template>
  </Suspense>
  <Suspense>
    <SolidityContracts />
    <template #fallback><p>Loading Solidity contracts...</p></template>
  </Suspense>
</template>

// examples/react/src/app.tsx
import { config } from "./config";
import { InkContracts } from "./ink-contract";
import { MultichainQuery } from "./multichain-query";
import { Mutation } from "./mutation";
import { Query } from "./query";
import { SolidityContracts } from "./solidity-contract";
import { WalletConnection } from "./wallet-connection";
import { MutationError, pending } from "@reactive-dot/core";
import {
  ChainProvider,
  ReactiveDotProvider,
  useMutationListener,
  useQueryErrorResetter,
} from "@reactive-dot/react";
import { DevTools } from "jotai-devtools";
import { Suspense } from "react";
import { ErrorBoundary, type FallbackProps } from "react-error-boundary";
import toast, { Toaster } from "react-hot-toast";

export function App() {
  return (
    <ReactiveDotProvider config={config}>
      <Suspense fallback="Loading wallet connection...">
        <WalletConnection />
      </Suspense>
      <ChainProvider chainId="polkadot">
        <Example chainName="Polkadot" />
      </ChainProvider>
      <ChainProvider chainId="kusama">
        <Example chainName="Kusama" />
      </ChainProvider>
      <ChainProvider chainId="westend">
        <Example chainName="Westend" />
      </ChainProvider>
      <ChainProvider chainId="pop_testnet">
        <Suspense fallback={<h2>Loading Pop Testnet...</h2>}>
          <h2>Pop Testnet</h2>
          <InkContracts />
        </Suspense>
      </ChainProvider>
      <ChainProvider chainId="passet_hub">
        <Suspense fallback={<h2>Loading Passet Hub...</h2>}>
          <h2>Passet Hub</h2>
          <SolidityContracts />
        </Suspense>
      </ChainProvider>
      <Toaster />
      <DevTools />
    </ReactiveDotProvider>
  );
}

type ExampleProps = { chainName: string };

function Example({ chainName }: ExampleProps) {
  const resetQueryError = useQueryErrorResetter();

  useMutationListener((event) => {
    if (event.value === pending) {
      toast.loading("Submitting transaction", { id: event.id });
      return;
    }

    if (event.value instanceof MutationError) {
      toast.error("Failed to submit transaction", { id: event.id });
      return;
    }

    switch (event.value.type) {
      case "finalized":
        if (event.value.ok) {
          toast.success("Submitted transaction", { id: event.id });
        } else {
          toast.error("Transaction failed", { id: event.id });
        }
        break;
      default:
        toast.loading("Transaction pending", { id: event.id });
    }
  });

  return (
    <div>
      <ErrorBoundary
        FallbackComponent={ErrorFallback}
        onReset={() => resetQueryError()}
      >
        <Suspense fallback={<h2>Loading {chainName}...</h2>}>
          <h2>{chainName}</h2>
          <Query />
          <MultichainQuery />
          <Mutation />
        </Suspense>
      </ErrorBoundary>
    </div>
  );
}

function ErrorFallback({ resetErrorBoundary }: FallbackProps) {
  return (
    <article>
      <header>
        <strong>Oops, something went wrong!</strong>
      </header>
      <button type="button" onClick={() => resetErrorBoundary()}>
        Retry
      </button>
    </article>
  );
}
